routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function () {
  return redirect('http://webmail.innsystem.com.br/');
});
Route::get('/admin', function () {
  return redirect('/dashboard');
});

Route::get('/manutencao', 'Front\HomeController@maintence');
Route::get('/', 'Front\HomeController@index')->name('home');

Route::get('/sobre', 'Front\AboutController@index');
Route::get('/planos', 'Front\HomeController@planos');

Route::get('/encontrar-estabelecimentos', 'Front\HomeController@index');
Route::get('/anunciar', 'Front\HomeController@anunciar');

Route::get('categorias', 'Front\CategoriesController@index');
Route::get('categorias/{slugCategoria}', 'Front\CategoriesController@show');
Route::get('categorias/{slugCategoria}/{slugEstabelecimento}', 'Front\CategoriesController@showEstablishment');
Route::get('estabelecimento/{slugEstablishment}', 'Front\CategoriesController@showEstablishmentTwo');

Route::get('calendario/', 'Front\CalendarsController@index');
Route::get('calendario/{slugCalendario}', 'Front\CalendarsController@showCalendar');

Route::get('blogs', 'Front\BlogsController@index');
Route::get('blogs/{slugBlog}', 'Front\BlogsController@show');
Route::get('/depoimentos', 'Front\ReviewController@index');
Route::post('/depoimentos-create', 'Front\ReviewController@store');
Route::get('/contato', 'Front\ContactController@index');

Route::get('/pagina/{slugPage}', 'Front\HomeController@pages');

Route::post('/estabelecimentos/busca', 'Front\HomeController@busca');
Route::get('/estabelecimentos/buscadistrito', 'Front\HomeController@buscadistrito');


Route::prefix('services')->namespace('Services')->group(function () {
  Route::post('send-mail', 'MailController@sendContact');
});




Auth::routes();

// Painel Administrativo
Route::prefix('dashboard')->middleware(['auth'])->group(function () {

  Route::get('/export-customers', 'Admin\DashboardController@exportCustomers')->name('export.customers');
  Route::get('/export-customers-establishments', 'Admin\DashboardController@exportCustomersEstablishments')->name('export.customers.establishments');

  // Geral
  Route::get('/', 'Admin\DashboardController@index');
  Route::resource('users', 'Admin\UsersController');
  Route::resource('pages', 'Admin\PagesController');
  Route::resource('configs', 'Admin\ConfigController');

  // Catalogo
  Route::resource('categories', 'Admin\CategoriesController');
  Route::delete('categories/{category}/photos/{photo}', 'Admin\\CategoriesController@photoRemove')->name('remove.photo');

  Route::resource('establishments', 'Admin\EstablishmentsController');
  Route::delete('establishments/{establishment}/photos/{photo}', 'Admin\\EstablishmentsController@photoRemove')->name('remove.photo');
  Route::post('establishments-upload/{establishment_id}', 'Admin\EstablishmentsController@upload')->name('admin-upload-miniaturas');
  Route::resource('customers', 'Admin\CustomersController');
  Route::resource('customerplans', 'Admin\CustomerPlansController');
  Route::resource('transations', 'Admin\TransationsController');
  Route::resource('plans', 'Admin\PlansController');

  Route::get('customerssetstatus', 'Admin\CustomersController@setstatus')->name('customers.setstatus');


  // Extras
  Route::resource('about', 'Admin\AboutController');
  Route::resource('blogs', 'Admin\BlogsController');
  Route::delete('blogs/{blog}/photos/{photo}', 'Admin\\BlogsController@photoRemove')->name('remove.photo');
  Route::resource('reviews', 'Admin\ReviewsController');
  Route::resource('sliders', 'Admin\SlidersController');
  Route::resource('apoios', 'Admin\ApoiosController');
  Route::resource('calendars', 'Admin\CalendarsController');
  Route::delete('calendars/{calendar}/photos/{photo}', 'Admin\\CalendarsController@photoRemove')->name('remove.photo');

  // Newsletter
  Route::prefix('newsletter')->group(function () {
    Route::get('list', 'Admin\NewsletterController@index');
    Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
    Route::get('generate-list', 'Admin\NewsletterController@generate');
    Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
  });
});

// Minha Conta
Route::prefix('minha-conta')->group(function () {
  // Login - Register
  Route::get('login', 'Customer\LoginController@login')->name('customer.auth.login');
  Route::post('login', 'Customer\LoginController@loginCustomer')->name('customer.auth.loginCustomer');
  Route::get('logout', 'Customer\LoginController@logout')->name('customer.auth.logout');
  // Registro
  Route::get('register', 'Customer\HomeController@create')->name('customer.register');
  Route::post('register', 'Customer\HomeController@store')->name('customer.register.store');

  // Reset
  Route::get('reset', 'Customer\ResetPasswordController@showLinkRequestForm')->name('customer.reset');
  Route::get('reset/new/{token}', 'Customer\ResetPasswordController@showResetForm')->name('customer.reset.new');
  Route::post('reset/request', 'Customer\ResetPasswordController@sendResetLinkEmail')->name('customer.reset.request');
  Route::post('reset/save', 'Customer\ResetPasswordController@saveNewPassword')->name('customer.reset.newpassword');



  Route::get('/', 'Customer\HomeController@index')->name('customer.dashboard');
  Route::resource('editar', 'Customer\HomeController');
  Route::post('cliente-deletar/{customer_id}', 'Customer\HomeController@destroy')->name('customer.destroy');
  Route::get('/plano/{estabelecimento_id}', 'Customer\HomeController@plan')->name('customer.plan');
  Route::get('/plano/contratar/{estabelecimento}', 'Customer\HomeController@planpayment')->name('customer.plan.payment');
  Route::get('/planoupgrades/{estabelecimento_id}', 'Customer\HomeController@upgrades')->name('customer.plan.upgrades');
  Route::get('/planoupgrades/contratar/{estabelecimento}', 'Customer\HomeController@upgradespayment')->name('customer.plan.upgradespayment');
  Route::get('/plano/renovar/{establishment_id}', 'Customer\HomeController@planrenew')->name('customer.plan.renew');
  Route::get('/plano/renovar/pagamento/{establishment_id}', 'Customer\HomeController@planrenewpayment')->name('customer.plan.renewpayment');
  Route::get('/planosuccess/sucesso', 'Customer\HomeController@plansuccess')->name('customer.plan.success');
  Route::get('/planosuccess/free', 'Customer\HomeController@planfree')->name('customer.plan.free');


  Route::get('/transacoes', 'Customer\HomeController@transation')->name('customer.transation');


  // Gerenciamento
  Route::resource('estabelecimentos', 'Customer\EstablishmentController');
  Route::get('estatisticas', 'Customer\EstablishmentController@statistics')->name('statistics');
  Route::delete('estabelecimentos/{establishment}/photos/{photo}', 'Customer\EstablishmentController@photoRemove')->name('remove.photo');

  Route::post('estabelecimentos-upload/{establishment_id}', 'Customer\EstablishmentController@upload')->name('upload-miniaturas');
});


// Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/base.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{{ $configs->config_description ?? '' }}">
  <meta name="keywords" content="{{ $configs->config_keywords ?? '' }}" />
  <title>{{ $configs->config_title ?? 'Catalogo Base' }} - Painel Administrativo</title>
  <link rel="shortcut icon" href="{{ asset('galerias/favicon.ico?6') }}" />
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <!-- ========== Css Files ========== -->
  <!-- <link href="{{ asset('backend/css/root.css?13') }}" rel="stylesheet"> -->
  <link href="{{ asset('backend/css/bootstrap.css?23') }}" rel="stylesheet">
  <link href="{{ asset('backend/css/style.css?23') }}" rel="stylesheet">
  <link href="{{ asset('backend/css/responsive.css?23') }}" rel="stylesheet">
  <link href="{{ asset('backend/css/shortcuts.css?23') }}" rel="stylesheet">
  <link href="{{ asset('backend/css/custons.css?23') }}" rel="stylesheet">
  @yield('cssPage')
</head>

<body>
  <div id="app" style="height:100%;">
    <!-- Start Page Loading -->
    <div class="loading"><img src="{{ asset('backend/img/loading.gif') }}" alt="loading-img"></div>
    <!-- End Page Loading -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->


    <!-- START TOP -->
    <div id="top" class="clearfix">
      <!-- Start Sidebar Show Hide Button -->
      <a href="#" class="sidebar-open-button"><i class="fa fa-bars"></i></a>
      <a href="#" class="sidebar-open-button-mobile"><i class="fa fa-bars"></i></a>
      <!-- End Sidebar Show Hide Button -->

      <!-- Start Sidepanel Show-Hide Button -->
      {{--<a href="#sidepanel" class="sidepanel-open-button"><i class="fa fa-outdent"></i></a>--}}
      <!-- End Sidepanel Show-Hide Button -->

      <!-- Start Top Right -->
      <ul class="top-right">
        <li class="dropdown link">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle profilebox"><b>{{ Auth::user()->name }}</b><span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-menu-list dropdown-menu-right">
            <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa falist fa-power-off"></i> Sair da Conta</a></li>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              {{ csrf_field() }}
            </form>
          </ul>
        </li>
      </ul>
      <!-- End Top Right -->
    </div>
    <!-- END TOP -->

    <!-- START SIDEBAR -->
    @include('admin.includes.sidebar-left')
    <!-- END SIDEBAR -->

    <!-- START CONTENT -->
    <div class="content">

      @yield('content')
      <!-- Start Footer -->
      <div class="row footer">
        <div class="col-md-6 text-left">
          {{ $configs->config_title ?? 'Catalogo Base' }} - Todos os Direitos Reservados {{ date('Y') }} ©
        </div>
        <div class="col-md-6 text-right">
          Desenvolvido por <a href="https://innsystem.com.br" target="_blank">InnSystem Inovação em Sistemas</a>
        </div>
      </div>
      <!-- End Footer -->

    </div>
    <!-- End Content -->



    <!-- START SIDEPANEL -->
    @include('admin.includes.sidebar-right')
    <!-- END SIDEPANEL -->
  </div>

  <script src="{{ mix('js/app.js') }}"></script>
  <script src="https://kit.fontawesome.com/04571ab3d2.js" crossorigin="anonymous"></script>
  <!-- //////////////////////////////////////////////////////////////////////////// -->
  <!-- ================================================
jQuery Library
================================================ -->
  <script type="text/javascript" src="{{ asset('backend/js/jquery.min.js') }}"></script>
  <!-- ================================================
Bootstrap Core JavaScript File
================================================ -->
  <script src="{{ asset('backend/js/bootstrap/bootstrap.min.js') }}"></script>
  <!-- ================================================
Plugin.js - Some Specific JS codes for Plugin Settings
================================================ -->
  <script type="text/javascript" src="{{ asset('backend/js/plugins.js') }}"></script>
  <script src="{{ asset('js/function_theme.js') }}"></script>
  <script type="text/javascript">
    $(function() {
      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        contentType: 'application/json'
      });
    })
  </script>
  <script src="{{ asset('js/jquery.maskedinput.js') }}"></script>
  <script>
    $(document).ready(function() {

      $('#config_phone').mask('(00) 0000-00009');
      $('#config_phone').blur(function(event) {
        if ($(this).val().length == 14) { // Celular com 9 dígitos + 2 dígitos DDD e 4 da máscara
          $('#config_phone').mask('(00) 0000-0000');
        } else {
          $('#config_phone').mask('(00) 90000-0000');
        }
      });

      $('#config_cellphone').mask('(00) 0000-00009');
      $('#config_cellphone').blur(function(event) {
        if ($(this).val().length == 14) { // Celular com 9 dígitos + 2 dígitos DDD e 4 da máscara
          $('#config_cellphone').mask('(00) 0000-0000');
        } else {
          $('#config_cellphone').mask('(00) 90000-0000');
        }
      });


      $('#phone').mask('(00) 0000-00009');
      $('#phone').blur(function(event) {
        if ($(this).val().length == 14) { // Celular com 9 dígitos + 2 dígitos DDD e 4 da máscara
          $('#phone').mask('(00) 0000-0000');
        } else {
          $('#phone').mask('(00) 90000-0000');
        }
      });

      $('#cellphone').mask('(00) 0000-00009');
      $('#cellphone').blur(function(event) {
        if ($(this).val().length == 14) { // Celular com 9 dígitos + 2 dígitos DDD e 4 da máscara
          $('#cellphone').mask('(00) 0000-0000');
        } else {
          $('#cellphone').mask('(00) 90000-0000');
        }
      });

      $('#hour').mask('00:00');

      $(".priceFormated").mask('####.##', {
        reverse: true
      });

      var options = {
        onKeyPress: function(cpfcnpj, e, field, options) {
          var masks = ['000.000.000-009', '00.000.000/0000-00'];
          var mask = (cpfcnpj.length > 14) ? masks[1] : masks[0];
          $('#document').mask(mask, options);
        }
      };

      $('#document').mask('000.000.000-009', options);

    });
  </script>

  @yield('jsPage')
</body>

</html>

resources/views/admin/dashboard.blade.php
@extends('admin.base')
@section('title', 'Painel de Controle')

@section('content')
<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-success">
        <div class="panel-heading">Seja bem vindo!</div>

        <div class="panel-body">
          Você está no seu <b>Painel Administrativo</b>, nessa área você terá acesso aos usuários administrativo cadastrados, toda a configuração geral do site e muitos outros recursos nesse completo Gerenciador de Conteúdo.
        </div>
      </div>
    </div>
  </div>

  <div class="row">
        <div class="col-md-12 col-lg-4 col-xl-4">
          <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
              <div class="widget-summary">
                <div class="widget-summary-col widget-summary-col-icon">
                  <div class="summary-icon bg-primary">
                    <i class="fa fa-users"></i>
                  </div>
                </div>
                <div class="widget-summary-col">
                  <div class="summary">
                    <h4 class="title">Clientes</h4>
                    <div class="info">
                      <strong class="amount">{{ $totalCustomers }}</strong>
                    </div>
                  </div>
                  <div class="summary-footer">
                    <a href="{{ route('customers.index') }}" class="text-muted text-uppercase">(ver todos)</a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <div class="col-md-12 col-lg-4 col-xl-4">
          <section class="panel panel-featured-left panel-featured-secondary">
            <div class="panel-body">
              <div class="widget-summary">
                <div class="widget-summary-col widget-summary-col-icon">
                  <div class="summary-icon bg-secondary">
                    <i class="fa fa-building"></i>
                  </div>
                </div>
                <div class="widget-summary-col">
                  <div class="summary">
                    <h4 class="title">Estabelecimentos</h4>
                    <div class="info">
                      <strong class="amount">{{ $totalEstablishments }}</strong>
                    </div>
                  </div>
                  <div class="summary-footer">
                  <a href="{{ route('establishments.index') }}" class="text-muted text-uppercase">(ver todos)</a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <div class="col-md-12 col-lg-4 col-xl-4">
          <section class="panel panel-featured-left panel-featured-tertiary">
            <div class="panel-body">
              <div class="widget-summary">
                <div class="widget-summary-col widget-summary-col-icon">
                  <div class="summary-icon bg-tertiary">
                    <i class="fa fa-shopping-cart"></i>
                  </div>
                </div>
                <div class="widget-summary-col">
                  <div class="summary">
                    <h4 class="title">Planos Ativos</h4>
                    <div class="info">
                      <strong class="amount">{{ $totalCustomerPlans }}</strong>
                    </div>
                  </div>
                  <div class="summary-footer">
                  <a href="{{ route('customerplans.index') }}" class="text-muted text-uppercase">(ver todos)</a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div><!-- row -->


  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">Próximos Vencimentos</div>

        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 col-md-12">
              <div class="table-responsiveoff">
                <table class="table table-hover table-striped table-bordered">
                  <thead>
                    <th><a href="{{ request()->fullUrlWithQuery(['column' => 'id', 'order' => $order]) }}"><i class="fas fa-sort"></i></a> #</th>
                    <th><a href="{{ request()->fullUrlWithQuery(['column' => 'cliente', 'order' => $order]) }}"><i class="fas fa-sort"></i></a> Cliente</th>
                    <th><a href="{{ request()->fullUrlWithQuery(['column' => 'estabelecimento', 'order' => $order]) }}"><i class="fas fa-sort"></i></a> Estabelecimento</th>
                    <th>Telefone</th>
                    <th><a href="{{ request()->fullUrlWithQuery(['column' => 'plano', 'order' => $order]) }}"><i class="fas fa-sort"></i></a> Plano</th>
                    <th><a href="{{ request()->fullUrlWithQuery(['column' => 'plan_dateend', 'order' => $order]) }}"><i class="fas fa-sort"></i></a> Vencimento</th>
                    <th>Valor</th>
                    <th width='5%'>Renov.</th>
                    <th>Status</th>
                    <th></th>
                  </thead>
                  <tbody>
                    @foreach($proxvencimentos as $proxvencimento)
                    <tr>
                      <td>{{ $proxvencimento->id }}</td>
                      <td>{{ $proxvencimento->cliente }} <a href="{{ route('customers.edit', $proxvencimento->clienteid) }}" class="btn-xs" data-toggle="tooltip" data-original-title="Editar Cliente"><i class="fa fa-edit"></i></a></td>
                      <td>{{ $proxvencimento->estabelecimento }} <a href="{{ route('establishments.edit', $proxvencimento->estabelecimentoid) }}" class="btn-xs" data-toggle="tooltip" data-original-title="Editar Estabelecimento"><i class="fa fa-edit"></i></a> </td>
                      @if($proxvencimento->iswhatsapp == 0)
                      <td><span class="label label-primary"><i class="fa fa-phone"></i></span> {{ $proxvencimento->phone }}</td>
                      @else
                      @php $retira = ["(", ")", " ", "-"]; @endphp
                      <td>
                      <a href="https://api.whatsapp.com/send?phone=55{{ str_replace($retira, '', $proxvencimento->phone) }}" target="_Blank">
                        <span class="label label-success"><i class="fab fa-whatsapp"></i></span>
                        {{ $proxvencimento->phone }}</a>
                      </td>
                      @endif
                      <td>{{ ($proxvencimento->plano ? $proxvencimento->plano : '-') }}</td>
                      <td>
                      @if($proxvencimento->plan_dateend)
                        <div id="dateAtual{{$proxvencimento->id}}">
                          {{ \Carbon\Carbon::parse($proxvencimento->plan_dateend)->format('d/m/y') }}
                        </div>
                        @else
                        -
                        @endif
                      </td>
                      <td>{{ ($proxvencimento->price ? $proxvencimento->price : '-')}}</td>
                      <td>{{ $proxvencimento->renews}} vezes</td>
                      <td>
                        <div class="btn-group pull-right">
                          <div id="statusAtual{{$proxvencimento->id}}" class="pull-left">
                            @if($proxvencimento->status == 'Pago')
                            <span class="label label-success">{{$proxvencimento->status}}</span>
                            @elseif($proxvencimento->status == 'Pendente')
                            <span class="label label-warning">{{$proxvencimento->status}}</span>
                            @elseif($proxvencimento->status == 'Aguardando')
                            <span class="label label-primary">{{$proxvencimento->status}}</span>
                            @elseif($proxvencimento->status == 'Expirado')
                            <span class="label label-danger">{{$proxvencimento->status}}</span>
                            @endif
                          </div>
                          @if($proxvencimento->plano)
                          <button type="button" data-toggle="dropdown" class="btn btn-xs btn-dark dropdown-toggle"><span class="caret"></span></button>
                          <ul class="dropdown-menu dropdown-menu-right">
                            <li><a class="ajaxstatus" data-customerplan_id="{{$proxvencimento->id}}" data-typestatus="Aguardando">Aguardando</a></li>
                            <li><a class="ajaxstatus" data-customerplan_id="{{$proxvencimento->id}}" data-typestatus="Pendente">Pendente</a></li>
                            <li><a class="ajaxstatus" data-customerplan_id="{{$proxvencimento->id}}" data-typestatus="Expirado">Expirado</a></li>
                            <li><a class="ajaxstatus" data-customerplan_id="{{$proxvencimento->id}}" data-typestatus="Pago">Pago</a></li>
                          </ul>
                          @endif
                        </div>
                      </td>
                      <td>
                        <a href="{{ route('customerplans.edit', $proxvencimento->id) }}" class="btn btn-xs btn-primary btn-icon" data-toggle="tooltip" data-original-title="Editar Plano"><i class="fa fa-edit"></i></a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <hr>
              <div class="row">
                <div class="col-xs-12 col-md-9">
                  {{ $proxvencimentos->appends(request()->except('page'))->links() }}
                </div>
                <div class="col-xs-12 col-md-3 pull-right text-right">
                  <p>Mostrando {{ count($proxvencimentos) }} de {{ $totalvencimentos }}</p>
                </div>
              </div>

            </div>
          </div><!-- row -->
        </div>
      </div>
    </div>
  </div>
</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection


@section('jsPage')
<script type="text/javascript">
  $('.ajaxstatus').click(function() {
    console.log('clicou');
    var customerplan_id = $(this).data("customerplan_id");
    var type_status = $(this).data("typestatus");

    $.ajax({
      url: '{{route('customers.setstatus')}}',
      type: 'get',
      data: {
        customerplan_id: customerplan_id,
        type_status: type_status,
      },
      dataType: 'html',
      success: function(html) {
        var dateend = JSON.parse(html).dateformat;
        if (html != '') {
          if (type_status == 'Pago') {
            $('#dateAtual' + customerplan_id).html('<span class="label label-success">' + dateend + '</span>');
            $('#statusAtual' + customerplan_id).html('<span class="label label-success">' + type_status + '</span>');
          } else if (type_status == 'Pendente') {
            $('#dateAtual' + customerplan_id).html('<span class="label label-warning">' + dateend + '</span>');
            $('#statusAtual' + customerplan_id).html('<span class="label label-warning">' + type_status + '</span>');
          } else if (type_status == 'Aguardando') {
            $('#dateAtual' + customerplan_id).html('<span class="label label-primary">' + dateend + '</span>');
            $('#statusAtual' + customerplan_id).html('<span class="label label-primary">' + type_status + '</span>');
          } else if (type_status == 'Expirado') {
            $('#dateAtual' + customerplan_id).html('<span class="label label-danger">' + dateend + '</span>');
            $('#statusAtual' + customerplan_id).html('<span class="label label-danger">' + type_status + '</span>');
          } else {
            $('#dateAtual' + customerplan_id).html('<span class="label label-default">' + dateend + '</span>');
            $('#statusAtual' + customerplan_id).html('<span class="label label-default">' + type_status + '</span>');
          }
        }
      }
    });
  });
</script>
@endsection